export const dataTab = [
  {
    productId: "01t1L00000M9BOtQAN",
    productName: "Geo Fee - Individual Delivery",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1a4AAB",
    PricebookEntry: null,
    calculatedPrice: 3.5,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 3.5,
    productOptionId: "a1z79000000CrtnAAC",
    Order__c: 2,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 3.5
  },
  {
    productId: "01t1L00000LOpHNQA1",
    productName: "Frequency Cap",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1aJAAR",
    PricebookEntry: null,
    calculatedPrice: 0,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 0,
    productOptionId: "a1z79000000CrtoAAC",
    Order__c: 3,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 0
  },
  {
    productId: "01t1V00000K3YBXQA3",
    productName: "Channel Block List",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1YsAAJ",
    PricebookEntry: null,
    calculatedPrice: 2,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 2,
    productOptionId: "a1z79000000CrtqAAC",
    Order__c: 5,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 2
  },
  {
    productId: "01t1V00000LGVorQAH",
    productName: "DAR TRC Only Custom Channel List",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000CuKKqAAN",
    PricebookEntry: null,
    calculatedPrice: 0,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 0,
    productOptionId: "a1z79000000CrtsAAC",
    Order__c: 7,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 0
  },
  {
    productId: "01t1V00000K3Z41QAF",
    productName: "DNA List (TRC)",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1a9AAB",
    PricebookEntry: null,
    calculatedPrice: 1,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 1,
    productOptionId: "a1z79000000CrttAAC",
    Order__c: 8,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 1
  },
  {
    productId: "01t1V00000K3Z4aQAF",
    productName: "3P Interactive (Innovid, Brightline)",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1a0AAB",
    PricebookEntry: null,
    calculatedPrice: 2.5,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 2.5,
    productOptionId: "a1z79000000CrtuAAC",
    Order__c: 9,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 2.5
  },
  {
    productId: "01t1V00000K3Z4BQAV",
    productName: "1P Interactive (OTT) - Direct to Product",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1aYAAR",
    PricebookEntry: null,
    calculatedPrice: 2,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 2,
    productOptionId: "a1z79000000CrtvAAC",
    Order__c: 10,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 2
  },
  {
    productId: "01t1V00000K3Z4GQAV",
    productName: "1P Interactive (OTT) - Direct to Store",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1ZgAAJ",
    PricebookEntry: null,
    calculatedPrice: 2,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 2,
    productOptionId: "a1z79000000CrtxAAC",
    Order__c: 11,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 2
  },
  {
    productId: "01t3w000006BlANAA0",
    productName: "Geo Fee - Fluid Delivery - Zip Code Targeting",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000CcW8oAAF",
    PricebookEntry: null,
    calculatedPrice: 3.5,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 3.5,
    productOptionId: "a1z79000000Cru1AAC",
    Order__c: 16,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 0,
    salesPrice: 3.5
  },
  {
    productId: "01t1V00000D7AgxQAF",
    productName: "Custom Channel List",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1aEAAR",
    PricebookEntry: null,
    calculatedPrice: 5,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 10,
    productOptionId: "a1z79000000CrtlAAC",
    Order__c: 1,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 100000,
    salesPrice: 10
  },
  {
    productId: "01t1L00000M9BOvQAN",
    productName: "Geo Fee - Fluid Delivery",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1ZzAAJ",
    PricebookEntry: null,
    calculatedPrice: 2,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 4,
    productOptionId: "a1z79000000CrtmAAC",
    Order__c: 1,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 40000,
    salesPrice: 4
  },
  {
    productId: "01t1V00000D7AgxQAF",
    productName: "Custom Channel List",
    productFamily: "Fee",
    rateType: "CPM",
    Product_Group__c: "No",
    OV_Fee_Percent__c: null,
    OV_3P_Data_Flag__c: false,
    fee_products_ids: null,
    pricebookEntryId: "01u3w00000Cu1aEAAR",
    PricebookEntry: null,
    calculatedPrice: 5,
    currencyCode: null,
    priceBookId: "01s3w000001hgFHAAY",
    discount: 0,
    accountPricebookId: null,
    discountScheduleEntryId: null,
    discountScheduleId: null,
    rateCardPrice: 10,
    productOptionId: "a1z79000000CrtrAAC",
    Order__c: 6,
    Bundled__c: true,
    Option_Group__c: "Fee",
    totalLevels: 2,
    productOptions: [],
    subTotal: 100000,
    salesPrice: 10
  }
];
